export const UserRoles = ['user', 'moderator', 'admin']
export const PriorityGroups = [
  "europe",
  "united states",
  "usa",
  "north-and-central-america",
  "america",
  "canada",
  "united kingdom",
  "england",
  "italy",
  "france",
  "germany",
  "spain",
  "belgium",
  "denmark",
  "finland",
  "sweden",
  "ireland",
  "netherlands",
  "austria",
  "czechia",
  "poland",
  "portugal",
  "romania",
  "slovakia",
  "switzerland",
  "hungary",
  "bulgaria",
  "croatia",
  "latvia",
  "lithuania",
  "estonia",
  "albania",
  "bosnia and herzegovina",
  "macedonia",
  "serbia",
  "montenegro",
  "cyprus",
  "greece",
];